"""
This type stub file was generated by pyright.
"""

from . import base
from git.types import Literal

__all__ = ("Blob",)

class Blob(base.IndexObject):
    """A Blob encapsulates a git blob object"""

    DEFAULT_MIME_TYPE = ...
    type: Literal[blob] = ...
    executable_mode = ...
    file_mode = ...
    link_mode = ...
    __slots__ = ...
    @property
    def mime_type(self) -> str:
        """
        :return: String describing the mime type of this file (based on the filename)
        :note: Defaults to 'text/plain' in case the actual file type is unknown."""
        ...
