---
site_name: SeaGOAT
repo_url: https://github.com/kantord/SeaGOAT
edit_uri: edit/main/docs/
extra:
    version:
        provider: mike
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - markdown_include.include:
          base_path: docs
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/logo.png
    palette:
        primary: cyan
    icon:
        edit: material/pencil
        view: material/eye
    features:
        - content.action.edit
        - content.code.copy
