"""
This type stub file was generated by pyright.
"""

import inspect
import os
import sys
import os.path as osp
from git.exc import *
from typing import Optional
from git.types import PathLike
from git.config import GitConfigParser
from git.objects import *
from git.refs import *
from git.diff import *
from git.db import *
from git.cmd import Git
from git.repo import Repo
from git.remote import *
from git.index import *
from git.util import Actor, BlockingLockFile, LockFile, Stats, rmtree

__version__ = ...
__all__ = [
    name
    for (name, obj) in locals().items()
    if not (name.startswith("_") or inspect.ismodule(obj))
]
GIT_OK = ...

def refresh(path: Optional[PathLike] = ...) -> None:
    """Convenience method for setting the git executable path."""
    ...
