---
name: Update AUR package

permissions:
    id-token: write
    contents: write

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    aur:
        runs-on: ubuntu-latest
        concurrency: release

        steps:
            - uses: actions/checkout@v3

            - name: Clone AUR package
              run: git clone https://aur.archlinux.org/python-seagoat.git

            - name: Update PKGBUILD
              run: |
                  ls
                  VERSION=$(grep "^version =" pyproject.toml | sed 's/version = "\(.*\)"/\1/')
                  echo $VERSION
                  sed -i "s/pkgver=.*/pkgver=$VERSION/g" python-seagoat/PKGBUILD
                  cat python-seagoat/PKGBUILD

            - name: Publish AUR package
              uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
              with:
                  pkgname: python-seagoat
                  pkgbuild: ./python-seagoat/PKGBUILD
                  commit_username: ${{ secrets.AUR_USERNAME }}
                  commit_email: ${{ secrets.AUR_EMAIL }}
                  ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
                  commit_message: Update AUR package
                  ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
